[package]
name = "domain_types"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["display", "constructor", "error"] }
num-traits = "0.2.19"
strum_macros = "0.27.1"
